-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 08:33:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria` DEFAULT CHARACTER SET utf8 ;
USE `concessionaria` ;

-- -----------------------------------------------------
-- Table `concessionaria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`clientes` (
  `idcliente` INT NOT NULL,
  `nomecliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`concessionaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`concessionaria` (
  `idconcessionaria` INT NOT NULL,
  `nomeconcessionaria` VARCHAR(45) NULL,
  PRIMARY KEY (`idconcessionaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`automoveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`automoveis` (
  `idautomoveis` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `preco` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idautomoveis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nomeusuario` VARCHAR(45) NULL,
  `senhausuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`alocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`alocacao` (
  `idalocacao` INT NOT NULL,
  `area` VARCHAR(45) NULL,
  `automoveis_idautomoveis` INT NOT NULL,
  `concessionaria_idconcessionaria` INT NOT NULL,
  `quantidade` INT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idalocacao`),
  INDEX `fk_alocacao_automoveis_idx` (`automoveis_idautomoveis` ASC),
  INDEX `fk_alocacao_concessionaria1_idx` (`concessionaria_idconcessionaria` ASC),
  INDEX `fk_alocacao_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_alocacao_automoveis`
    FOREIGN KEY (`automoveis_idautomoveis`)
    REFERENCES `concessionaria`.`automoveis` (`idautomoveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alocacao_concessionaria1`
    FOREIGN KEY (`concessionaria_idconcessionaria`)
    REFERENCES `concessionaria`.`concessionaria` (`idconcessionaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alocacao_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `concessionaria`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
